// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAplQKq6HHbOJGOOvRysviRxvKtylQMHHU',
    appId: '1:335724441891:web:c1e2ddb065b4081c651c96',
    messagingSenderId: '335724441891',
    projectId: 'beam-87865',
    authDomain: 'beam-87865.firebaseapp.com',
    storageBucket: 'beam-87865.firebasestorage.app',
    measurementId: 'G-WBHYTERJCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwHPDEGYp_lbY67ufRdJEoQCbVCJNb-Y',
    appId: '1:335724441891:android:c7849dab210e3aab651c96',
    messagingSenderId: '335724441891',
    projectId: 'beam-87865',
    storageBucket: 'beam-87865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEz2Br3O1ueR-n2ydQNHqN4_dpXb173M',
    appId: '1:335724441891:ios:94a59acc333c10c6651c96',
    messagingSenderId: '335724441891',
    projectId: 'beam-87865',
    storageBucket: 'beam-87865.firebasestorage.app',
    iosBundleId: 'com.example.roadapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEz2Br3O1ueR-n2ydQNHqN4_dpXb173M',
    appId: '1:335724441891:ios:94a59acc333c10c6651c96',
    messagingSenderId: '335724441891',
    projectId: 'beam-87865',
    storageBucket: 'beam-87865.firebasestorage.app',
    iosBundleId: 'com.example.roadapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAplQKq6HHbOJGOOvRysviRxvKtylQMHHU',
    appId: '1:335724441891:web:525746917d7fc485651c96',
    messagingSenderId: '335724441891',
    projectId: 'beam-87865',
    authDomain: 'beam-87865.firebaseapp.com',
    storageBucket: 'beam-87865.firebasestorage.app',
    measurementId: 'G-KBYXCZJZ8Z',
  );
}
